### ISSUE TITLE
looking forward for updating your github

### ISSUE THREAD

**Issue by Fotouhif** [thunlp/AdversarialTaboo#1]
Hello,

Thank you for making this repository. I went through your article which was very interesting to me. 
I am working on the same topic right now and I was wondering when you plan to update your repository. 

Thank you very much,
Fateme

**Comment by yaoyuanTHU** [comment]
Hi Fateme, Thanks for the interest. Sorry for not timely updating the repo, since I have been quite busy recently. I will try to update the repo before May. Thanks.

**Comment by BugraHamza** [comment]
Hello,

It is almost 2022 but the repo is still not updated. Could you inform us when the update will come?

Thanks
Buura

**Comment by Guaguago** [comment]
Interesting paper,  look forwrd to the code, inform us when the update will come?  thank you very much.

**Comment by HernandezEduin** [comment]
Any updates on the upload status? We are looking forwards to the code implementation.

**Comment by yaoyuanTHU** [comment]
Hi. Thanks for the interest. I'm currently working on releasing the code. It will hopefully be ready within a month. Thanks again for the attention.

**Comment by yaoyuanTHU** [comment]
Hi all, the code and data have been uploaded. Thanks for your interest.
